[package]
name = "graph_csr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easy_mmap = "0.2.3"
rand = "0.8.5"
num-traits = "0.2"